name: Java CI/CD

on:
  push:
    branches:
      - main
      - develop/*
      - release/*
  pull_request:
    branches:
      - main
      - develop/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Build
        run: mvn clean install
