name: Java CI/CD

on:
  push:
    branches:
      - main
      - develop/*
      - release/*
  pull_request:
    branches:
      - main
      - develop/*
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine build tool
        id: determine_build_tool
        run: |
          if [ -f "build.gradle" ]; then
            echo "::set-output name=build_tool::gradle"
          elif [ -f "pom.xml" ]; then
            echo "::set-output name=build_tool::maven"
          else
            echo "Unsupported build tool"
            exit 1
          fi

      - name: Build
        if: steps.determine_build_tool.outputs.build_tool == 'gradle'
        run: ./gradlew build
      - name: Build
        if: steps.determine_build_tool.outputs.build_tool == 'maven'
        run: mvn clean install
