name: Java CI/CD

on:
  push:
    branches:
      - main
      - develop/*
      - release/*
  pull_request:
    branches:
      - main
      - develop/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install
