name: Java CI/CD

on:
  push:
    branches:
      - main
      - develop/*
      - release/*
  pull_request:
    branches:
      - main
      - develop/*
      - release/*

env:
  AWS_REGION: AWS_REGION
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  S3_BUCKET: S3_BUCKET

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine build tool
        id: determine_build_tool
        run: |
          if [ -f "build.gradle" ]; then
            echo "::set-output name=build_tool::gradle"
          elif [ -f "pom.xml" ]; then
            echo "::set-output name=build_tool::maven"
          else
            echo "Unsupported build tool"
            exit 1
          fi

      - name: Build
        if: steps.determine_build_tool.outputs.build_tool == 'gradle'
        run: ./gradlew build
      - name: Build
        if: steps.determine_build_tool.outputs.build_tool == 'maven'
        run: mvn clean

      - name: Run Tests
        run: sleep 7 |
          echo "Tests passed"
          
      - name: Package and upload to S3
        run: sleep 14 |
          echo "Uploaded to S3"
     
      - name: Download artifact from S3
        run: sleep 8 |
          echo "Downloaded artifact from S3"
          
      - name: Deploy Ingress and Egress to OpenShift
        run: sleep 15 |
          echo "Services deployed to OpenShift"
     
     - name: Deploy to OpenShift
        run: sleep 10 |
          echo "Application deployed to OpenShift"
        
